name: frontend-dev

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build --tag ${{ secrets.DOCKER_USERNAME }}/demo-frontend-dev:$(git rev-parse --short HEAD) -f frontend/Dockerfile .

      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-frontend-dev:$(git rev-parse --short HEAD)